# To use the KafkaConnector resource, you have to first enable the connector operator using
# the strimzi.io/use-connector-resources annotation on the KafkaConnect custom resource.
# From Apache Kafka 3.1.1 and 3.2.0, you also have to add the FileStreamSourceConnector
# connector to the container image. You can do that using the kafka-connect-build.yaml example.
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: sunki-connector
  labels:
    # The strimzi.io/cluster label identifies the KafkaConnect instance
    # in which to create this connector. That KafkaConnect instance
    # must have the strimzi.io/use-connector-resources annotation
    # set to true.
    strimzi.io/cluster: sunki-cluster
spec:
  class: com.rue.sunki.kafka.connector.MqttSourceConnector
  tasksMax: 3
  autoRestart:
    enabled: true
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    kafka.topic: machine
    mqtt.topic.prefix: machine
    mqtt.port: 1883
#    TODO: CURRENTLY THIS DOES NOT WORK. To run, we need the literal String values.
#    TODO: Support the following as described here https://strimzi.io/docs/operators/latest/configuring.html#type-ExternalConfigurationEnv-reference
    mqtt.host: "${file:/opt/kafka/external-configuration/mqtt-credentials/mqtt.host}"
    mqtt.username: "${file:/opt/kafka/external-configuration/mqtt-credentials/sunki-secret:mqtt.username}"
    mqtt.password: "${file:/opt/kafka/external-configuration/mqtt-credentials/sunki-secret:mqtt.password}"