apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sunki-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /sunki/actuator
            backend:
              service:
                name: sunki-service
                port:
                  name: actuator
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sunki-service
                port:
                  name: broker