apiVersion: v1
kind: ConfigMap
metadata:
  name: sunki-mqtt-conf
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sunki-mqtt-host
data:
  mqtt.host: 'sunki-service'