apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomelo
  labels:
    app: pomelo
spec:
  replicas: 1
  template:
    metadata:
      name: pomelo
      labels:
        app: pomelo
    spec:
      containers:
        - name: pomelo
          image: localhost:5001/pomelo:latest
          imagePullPolicy: Always
          ports:
            - name: kafka-cluster
              containerPort: 9092
            - name: actuator
              containerPort: 8085
#          resources:
#            limits:
#              cpu: 500m
#            requests:
#              cpu: 50m
          env:
            - name: fetch.max.bytes
              value: '524288000'
            - name: max.partition.fetch.bytes
              value: '104857600'
            - name: fetch.max.wait.ms
              value: '500'
            - name: topology.optimize
              value: 'all'
            - name: kafka.bootstrap.servers
              valueFrom:
                secretKeyRef:
                  name: pomelo-secret
                  key: kafka.bootstrap.servers
                  optional: false
            - name: kafka.group.id
              valueFrom:
                secretKeyRef:
                  name: pomelo-secret
                  key: kafka.group.id
                  optional: false
            - name: kafka.topic
              valueFrom:
                secretKeyRef:
                  name: pomelo-secret
                  key: kafka.topic
                  optional: false
            - name: num.threads
#              value: '1'
              valueFrom:
                secretKeyRef:
                  name: pomelo-secret
                  key: num.threads
                  optional: false
      restartPolicy: Always
  selector:
    matchLabels:
      app: pomelo
