apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pomelo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pomelo
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: External
      external:
        metric:
          name: kafka_lag
          selector:
            matchLabels:
              topic: machine.0
        target:
          type: AverageValue
          averageValue: "15"