apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomelo
  labels:
    app: pomelo
spec:
  replicas: 2
  template:
    metadata:
      name: pomelo
      labels:
        app: pomelo
    spec:
      containers:
        - name: pomelo
          image: localhost:5001/pomelo:latest
          imagePullPolicy: Always
          ports:
            - name: kafka-cluster
              containerPort: 9092
            - name: actuator
              containerPort: 8085
          env:
            - name: fetch.max.bytes
              valueFrom:
                configMapKeyRef:
                  name: pomelo-conf
                  key: fetch.max.bytes
                  optional: false
            - name: max.partition.fetch.bytes
              valueFrom:
                configMapKeyRef:
                  name: pomelo-conf
                  key: max.partition.fetch.bytes
                  optional: false
            - name: connections.max.idle.ms
              valueFrom:
                configMapKeyRef:
                  name: pomelo-conf
                  key: connections.max.idle.ms
                  optional: false
            - name: fetch.max.wait.ms
              valueFrom:
                configMapKeyRef:
                  name: pomelo-conf
                  key: fetch.max.wait.ms
                  optional: false
            - name: topology.optimize
              valueFrom:
                configMapKeyRef:
                  name: pomelo-conf
                  key: topology.optimize
                  optional: false
            - name: kafka.bootstrap.servers
              valueFrom:
                configMapKeyRef:
                  name: pomelo-conf
                  key: kafka.bootstrap.servers
                  optional: false
            - name: kafka.group.id
              valueFrom:
                configMapKeyRef:
                  name: pomelo-conf
                  key: kafka.group.id
                  optional: false
            - name: kafka.topic
              valueFrom:
                configMapKeyRef:
                  name: pomelo-conf
                  key: kafka.topic
                  optional: false
            - name: num.threads
              valueFrom:
                configMapKeyRef:
                  name: pomelo-conf
                  key: num.threads
                  optional: false
      restartPolicy: Always
  selector:
    matchLabels:
      app: pomelo
