apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pomelo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pomelo
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
#    - type: Resource
#      resource:
#        name: memory
#        target:
#          type: Utilization
#          averageUtilization: 100
#    - type: Pods
#      pods:
#        metric:
#          name: packets-per-second
#        target:
#          type: AverageValue
#          averageValue: "100"
