# https://medium.com/@roman.noze/kubernetes-pods-autoscaling-with-kafka-metrics-9b7d5ec3c1d3
apiVersion: v1
data:
#  TODO: Clean up
  config.yaml: |-
    externalRules:
      - seriesQuery: '{topic!="",__name__=~"kafka_consumergroup_lag"}'
      #    seriesQuery: '{__name__=~"kafka_consumergroup_lag"}'
        resources:
          template: <<.Resource>>
    #      overrides:
    #        namespace: { resource: "namespace" }
    #        pod: { resource: "pod" }
    #    metricsQuery: sum(kafka_consumergroup_lag) by (<<.GroupBy>>)
        metricsQuery: sum(min_over_time(kafka_consumergroup_lag{<< range $key, $value :=.LabelValuesByName >><< if ne $key "namespace" >><< $key >>="<< $value >>",<<end >><< end >>}[1h])) by (topic,consumergroup)
        
        name:
          as: kafka_lag
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: metrics-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/version: 0.10.0
  name: adapter-config
  namespace: default
