kind: Pod
apiVersion: v1
metadata:
  name: pomelo-pod
  labels:
    app: pomelo
spec:
  containers:
    - name: pomelo
      image: localhost:5001/pomelo:latest
      imagePullPolicy: IfNotPresent
#      ports:
#        - containerPort: 1883
#        - containerPort: 8081
      env:
        - name: kafka.bootstrap.servers
          valueFrom:
            secretKeyRef:
              name: pomelo-secret
              key: kafka.bootstrap.servers
              optional: false
        - name: kafka.group.id
          valueFrom:
            secretKeyRef:
              name: pomelo-secret
              key: kafka.group.id
              optional: false
        - name: kafka.topic
          valueFrom:
            secretKeyRef:
              name: pomelo-secret
              key: kafka.topic
              optional: false