kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pomelo-cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
      endpoint = ["http://citrus-registry:5000"]